---
abstract: 'gather smoking statistics from minismokebox'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SmokeBox-Mini-Plugin-Stats
requires:
  App::SmokeBox::Mini: 0.32
  App::SmokeBox::Mini::Plugin: 0.32
  DBD::SQLite: 1.31
  DBI: 1.614
  POE: 1.293
  POE::Component::EasyDBI: 1.23
  Time::HiRes: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/app-smokebox-mini-plugin-stats
  repository: https://github.com/bingos/app-smokebox-mini-plugin-stats
version: 0.10
